# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Make-ChatRooms' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Make-ChatRooms
  pod 'Socket.IO-Client-Swift'

  target 'Make-ChatRoomsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Socket.IO-Client-Swift'
  end

end
