# This .goreleaser.yml was customized by @droxey to ensure smooth deployments on Homebrew!
before:
  hooks:
    - go mod tidy # Cleanup dependencies.
    - go mod download # Install dependencies.
builds:
  - id: hellohomebrew-darwin-amd64 # Format: reponame-envname-platform
    binary: hellohomebrew # Same as project name.
    env:
      - CGO_ENABLED=0
    main: ./main.go # Where func main() lives.
    goos:
      - darwin # Install for macOS.
    goarch:
      - amd64 # Only modern macOS.
    ignore:
      - goos: Darwin # Skip old macOS.
        goarch: 386 # Skip old macOS.
brews:
  - github:
      owner: TODO_GITHUB_USERNAME
      name: homebrew-hellohomebrew
    folder: Formula
    homepage: https://github.com/TODO_GITHUB_USERNAME/homebrew-hellohomebrew
    description: BEW 2.5 - Homebrew Hello World
archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: "{{.ProjectName}}_{{.Version}}_{{.Os}}-{{.Arch}}"
    replacements:
      amd64: 64bit
      386: 32bit
      arm: ARM
      arm64: ARM64
      darwin: macOS
      linux: Linux
      windows: Windows
      openbsd: OpenBSD
      netbsd: NetBSD
      freebsd: FreeBSD
      dragonfly: DragonFlyBSD
    files:
      - README.md
      - LICENSE
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "README"
      - Merge pull request
      - Merge branch
