# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'voicy-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Moya', '~> 10.0'

  target 'voicy-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
